#@ load("@ytt:data", "data")

#@ imageCaching = getattr(data.values, "imageCaching", True)
#@ localContent = getattr(data.values, "localContent", False)

---
apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-builtin-vcluster"
spec:
  title: "Test of builtin virtual cluster"
  description: "Test of using builtin support for creating a virtual cluster."
  publish:
    image: $(image_repository)/labs-vcluster-testing/lab-builtin-vcluster-files:$(workshop_version)
    files:
    - directory:
        path: workshop
      path: workshop
  workshop:
    files:
    #@ if imageCaching:
    - http:
        url: http://$(assets_repository)/.tgz
    #@ else:
    - image:
        url: $(image_repository)/labs-vcluster-testing/lab-builtin-vcluster-files:$(workshop_version)
    #@ end
  session:
    namespaces:
      budget: medium
      security:
        token:
          enabled: false
    applications:
      workshop:
        enabled: true
        #@ if localContent:
        proxy:
          protocol: http
          host: localhost.$(ingress_domain)
          port: 10081
          changeOrigin: false
          headers:
          - name: X-Session-Name
            value: $(session_name)
        #@ end
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: true
      vcluster:
        enabled: true
  environment:
    assets:
      files:
      #@ if imageCaching:
      - image:
          url: $(image_repository)/labs-vcluster-testing/lab-builtin-vcluster-files:$(workshop_version)
      #@ end
