#@ load("@ytt:data", "data")

#@ imageCaching = getattr(data.values, "imageCaching", True)

---
apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-admin-vcluster"
spec:
  title: "Test of admin virtual cluster"
  description: "Test of shared virtual cluster providing full admin access."
  publish:
    image: $(image_repository)/labs-vcluster-testing/lab-admin-vcluster-files:$(workshop_version)
    files:
    - directory:
        path: workshop
      path: workshop
    - directory:
        path: ../../packages
      path: packages
  workshop:
    files:
    #@ if imageCaching:
    - http:
        url: http://$(assets_repository)/.tgz
      includePaths:
      - workshop/**
    #@ else:
    - image:
        url: $(image_repository)/labs-vcluster-testing/lab-admin-vcluster-files:$(workshop_version)
      includePaths:
      - workshop/**
    #@ end
  session:
    namespaces:
      budget: large
      security:
        policy: baseline
        token:
          enabled: false
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: true
        vendor: octant
        octant:
          version: latest
      vcluster:
        enabled: false
    volumes:
    - name: admin-credentials-config
      secret:
        secretName: $(session_name)-kubeconfig
    - name: session-credentials-config
      emptyDir: {}
    volumeMounts:
    - name: admin-credentials-config
      mountPath: /opt/kubeconfig
    objects:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: $(session_name)-admin-vcluster-values
        namespace: $(workshop_namespace)
      stringData:
        values.yaml: |
          vcluster:
            image: rancher/k3s:v1.25.3-k3s1
          syncer:
            extraArgs:
            - --tls-san=admin-vcluster.$(session_namespace).svc.$(cluster_domain)
            - --out-kube-config-server=https://admin-vcluster.$(session_namespace).svc.$(cluster_domain)
    - apiVersion: kappctrl.k14s.io/v1alpha1
      kind: App
      metadata:
        name: $(session_name)-admin-vcluster-package
        namespace: $(workshop_namespace)
      spec:
        serviceAccountName: kapp-installer
        syncPeriod: 720h
        noopDelete: true
        fetch:
        - helmChart:
            name: vcluster
            repository:
              url: https://charts.loft.sh
        template:
        - helmTemplate:
            name: admin-vcluster
            namespace: $(session_namespace)
            valuesFrom:
            - secretRef:
                name: $(session_name)-admin-vcluster-values
        deploy:
        - kapp:
            rawOptions:
            - --app-changes-max-to-keep=5
    - apiVersion: secrets.educates.dev/v1beta1
      kind: SecretCopier
      metadata:
        name: $(session_name)-kubeconfig
      spec:
        rules:
        - sourceSecret:
            name: vc-admin-vcluster
            namespace: $(session_namespace)
          targetNamespaces:
            nameSelector:
              matchNames:
              - $(workshop_namespace)
          targetSecret:
            name: $(session_name)-kubeconfig
  environment:
    assets:
      files:
      - image:
          url: $(image_repository)/labs-vcluster-testing/lab-admin-vcluster-files:$(workshop_version) 
    objects:
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kapp-installer
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: kapp-installer-$(workshop_namespace)
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: kapp-installer
          namespace: $(workshop_namespace)
