apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: labs-vcluster-testing
spec:
  portal:
    registration:
      type: anonymous
    updates:
      workshop: true
    sessions:
      maximum: 1
    workshop:
      defaults:
        reserved: 0
  workshops:
  - name: lab-builtin-vcluster
    expires: 40m
    overtime: 10m
    deadline: 60m
    orphaned: 5m
  - name: lab-shared-vcluster
    expires: 40m
    overtime: 10m
    deadline: 60m
    orphaned: 5m
  - name: lab-remote-cluster
    expires: 40m
    overtime: 10m
    deadline: 60m
    orphaned: 5m
