#@ load("@ytt:data", "data")

#@ for name in data.values.namespaces:
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-session-role
  namespace: #@ name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: #@ data.values.developer
  namespace: default
#@ end
