#@ load("@ytt:data", "data")
---
apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: #@ "deny-ingress-{}.educates.dev".format(data.values.session)
spec:
  operations: ["CREATE"]
  resources: ["ingresses"]
  scope: Namespaced
  namespaceSelector:
    matchNames: #@ data.values.namespaces
  #@yaml/text-templated-strings
  javascript: |
    request.object.spec.rules.forEach(function(item) {
      if (item.host.indexOf("(@= data.values.session @)") == -1) {
        deny("Ingress host name must embed the workshop session name.");
      }
    })
