#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

---
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials-3
  namespace: default
data:
  GIT_PROTOCOL: #@ base64.encode(data.values.GIT_PROTOCOL)
  GIT_HOST: #@ base64.encode(data.values.GIT_HOST)
  GIT_USERNAME: #@ base64.encode(data.values.GIT_USERNAME)
  GIT_PASSWORD: #@ base64.encode(data.values.GIT_PASSWORD)
