apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-setup-vcluster"
spec:
  title: "Test of setting up a virtual cluster"
  description: "Test of how to prepopulate a virtual cluster with resources."
  publish:
    image: $(image_repository)/labs-vcluster-testing/lab-setup-vcluster-files:$(workshop_version)
    files:
    - directory:
        path: .
      includePaths:
      - /workshop/**
      - /resources/**
      - /templates/**
      - /README.md
      excludePaths:
      - /workshop/.hugo_build.lock
      - /workshop/resources/**
  workshop:
    files:
    - image:
        url: $(image_repository)/labs-vcluster-testing/lab-setup-vcluster-files:$(workshop_version)
  session:
    namespaces:
      budget: medium
      security:
        token:
          enabled: false
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
      vcluster:
        enabled: true
        objects:
        - apiVersion: v1
          kind: Secret
          metadata:
            name: git-credentials-1
            namespace: default
          stringData:
            GIT_PROTOCOL: $(git_protocol)
            GIT_HOST: $(git_host)
            GIT_USERNAME: $(git_username)
            GIT_PASSWORD: $(git_password)
      git:
        enabled: true
      files:
        enabled: true
    objects:
    - apiVersion: kappctrl.k14s.io/v1alpha1
      kind: App
      metadata:
        name: kapp-controller
        namespace: $(session_namespace)-vc
      spec:
        noopDelete: true
        syncPeriod: 24h
        cluster:
          namespace: default
          kubeconfigSecretRef:
            name: $(vcluster_secret)
            key: config
        fetch:
        - http:
            url: https://github.com/carvel-dev/kapp-controller/releases/download/v0.44.9/release.yml
        template:
        - ytt: {}
        deploy:
        - kapp: {}
    - apiVersion: v1
      kind: Secret
      metadata:
        name: credentials-data-values
        namespace: $(session_namespace)-vc
      stringData:
        values.yaml: |
          GIT_PROTOCOL: $(git_protocol)
          GIT_HOST: $(git_host)
          GIT_USERNAME: $(git_username)
          GIT_PASSWORD: $(git_password)
    - apiVersion: kappctrl.k14s.io/v1alpha1
      kind: App
      metadata:
        name: git-credentials-2
        namespace: $(session_namespace)-vc
      spec:
        noopDelete: true
        syncPeriod: 24h
        cluster:
          namespace: default
          kubeconfigSecretRef:
            name: $(vcluster_secret)
            key: config
        fetch:
        - image:
            url: $(image_repository)/labs-vcluster-testing/lab-setup-vcluster-files:$(workshop_version)
        template:
        - ytt:
            valuesFrom:
            - secretRef:
                name: credentials-data-values
            paths:
            - templates/git-credentials-2.yaml
        deploy:
        - kapp: {}
    - apiVersion: kappctrl.k14s.io/v1alpha1
      kind: App
      metadata:
        name: git-credentials-3
        namespace: $(session_namespace)-vc
      spec:
        noopDelete: true
        syncPeriod: 24h
        cluster:
          namespace: default
          kubeconfigSecretRef:
            name: $(vcluster_secret)
            key: config
        fetch:
        - http:
            url: $(session_url)/files/objects/git-credentials-3.yaml?token=$(services_password)
        template:
        - ytt: {}
        deploy:
        - kapp: {}
